- CHANGELOG.md
- README.md
- octodns_ns1/__init__.py
- requirements.txt
- setup.py
- tests/test_provider_ns1.py
/cc https://github.com/octodns/octodns/pull/876 which adds the underlying support 
/cc https://github.com/octodns/octodns/issues/38 which tracks the broader functionality request
> Enable SUPPORTS_ROOT_NS to allow managing root NS records

- setup.py
`requirements.txt` contains the `requests` module as a dependency.  but it is missing in the setup.py. 
If you run octodns for NS1 provider without requests it fails when it needs to create a new zone in NS1.
https://github.com/octodns/octodns-ns1/issues/14
> add missing required module in setup.py

- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Not all records have `short_answers` so we need to avoid the `KeyError` on those that don't. This also adds a test case from the problematic record provided in https://github.com/octodns/octodns-ns1/issues/17 and fixes some ~bugs in the existing test code where answers weren't what they were expected to be (likely copy-n-paste errors.)
/cc https://github.com/octodns/octodns-ns1/issues/17 @flz
> Don't fail on unsupported tier > 1 records in populate

- CHANGELOG.md
- README.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
== Problem ==
Currently NS1 monitors generated by octodns-ns1 use HTTP 1.0 (smuggled over a TCP connection). This does not work when pointing to Azure Storage accounts. This ticket is to create a PR to change these monitors to use HTTP 1.1
== Example ==
NS1 doesn't actually create HTTP monitors, instead prefering to create TCP monitors and manually constructing HTTP messages on top. We can emulate sending a monitor ping to an Azure storage blob using `ncat`:
```
$ printf 'GET /admin HTTP/1.0\r\nHost: <storageaccountnamehere>.z5.web.core.windows.net\r\nUser-agent: NS1\r\n\r\n' | ncat --ssl <storageaccountnamehere>.z5.web.core.windows.net 443
HTTP/1.1 505 The HTTP version specified is not supported for this operation by the server.
Content-Length: 369
Content-Type: text/html
Server: …
```
> Use HTTP 1.1 in for NS1 dynamic DNS HTTPS monitors

- CHANGELOG.md
- octodns_ns1/__init__.py
* Enable SUPPORTS_ROOT_NS for management of root NS records. Requires
octodns>=0.9.16.
* Configurable http version for dynamic HTTPS monitors, to enable HTTP/1.1 support
> v0.0.3 version bump and CHANGELOG update

- .git-blame-ignore-revs
- octodns_ns1/__init__.py
- pyproject.toml
- requirements-dev.txt
- script/coverage
- script/format
- script/test
- setup.py
- tests/test_provider_ns1.py
Fairly happy with the results here. If we want to go forward with this it'll need ported over into https://github.com/octodns/octodns-template and https://github.com/octodns/octodns and then applied to a whole bunch of repos.
/cc https://github.com/octodns/octodns-ns1/pull/29#issuecomment-1398733596 @bkane-msft for the suggestion
> Explore using isort to manage imports

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Notes was returning "10" (str) which doesn't sort numerical
/cc Fixes https://github.com/octodns/octodns-ns1/issues/35 @istr
> Fix for rule ordering when there's > 10 rules

- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Cribbed from https://github.com/octodns/octodns-ns1/issues/35#issuecomment-1487065395
The false/persistent update is coming from `_extra_changes` 
```console
2023-03-28T07:55:32  [4644720128] INFO  Ns1Provider[ns1] _extra_changes: monitor mis-match for a.exxampled.com - A - 1.1.1.1
```
Which is triggered when `_monitor_is_match` returns `False`:
https://github.com/octodns/octodns-ns1/blob/bc542be4ac73d3914adcfd5d1ce2f56ff484e119/octodns_ns1/__init__.py#L1196-L1203
Printing out the two
```python
{'expected': {'active': True,
'config': {'connect_timeout': 2000,
'host': '1.1.1.1',
'port': 443,
'response_timeout': 10000,
'send': 'GET /_dns HTTP/1.0\\r\\nHost: '
'a.exxampled.com\\r\\nUser-agent: '
'NS1\\r\\n\\r\\n',
'ssl': True},
'frequency': 60,
'job_type': 'tcp',
'name': 'a.exxampled.com - A …
```
> _monitor_is_match needs to use expected for nested dict `config` too

- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
This is part 1 of 2 related to https://github.com/octodns/octodns-ns1/issues/38. It moves NS1's contient -> country mappings to be sourced from `octodns.record.geo_data` rather than duplicating the data.
It also moves `UM` from `NA` which it is politically related to to `OC` which it is geographically located in.
/cc https://github.com/octodns/octodns-ns1/issues/38 which lead to this change
/cc @viranch @istr
> Use geo data

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
- country_alpha2_to_continent_code didn't support TL, add it to the manual list
- rework some tests that were using AS as a region to use SA instead
- explicitly test _parse_rule_geos special_cases
/cc https://github.com/octodns/octodns-ns1/pull/40 which this builds on
/cc https://github.com/octodns/octodns-ns1/issues/38 which lead to this change
/cc @viranch @istr
> AS as a country list rather than ASIAPAC region, fix TL

- CHANGELOG.md
- octodns_ns1/__init__.py
Make synthetic ocean region work by moving the more specific rules to the top.
Fixes #36
> Revert order of self._COUNTRY_FILTER and self._REGION_FILTER

- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
`_params_for_A` was mistakenly looking for only the presence of `.geo` and its truthiness. It'll always be present on `A` and `AAAA` records, but only truthy when `geo` functionality is used. It just so happens that `_params_for_geo_A` returned valid params for the case when there were no geos so things worked. That said it returned extra information and was confusing and not the intended/expected flow.
This fixes that issue and checks that `geo` is present and truthy before using that path.
This was found while digging into hiccups in https://github.com/octodns/octodns-ns1/pull/45. The test side of things will change slightly back towards what I'm removing here, but that's fine and it's cleaner to fix things standalone in main before that change lands. 
/cc …
> Make sure geo is truthy, not just present

- CHANGELOG.md
- octodns_ns1/__init__.py
* Dynamic records filter chain ordering reworked to place country filters before
regions, see https://github.com/octodns/octodns-ns1/pull/37 for
details/discussion.
* AS implemented as a list of countries rather than the ASIAPAC region which
didn't match as the AS list of countries in the first place
* AS, NA, and OC source their list of countries from octodns.record.geo_data
rather than manually duplicating the information here.
* Add TL to the list of special case countries so that it can be individually
targeted
* Fix for rule ordering when there's > 10 rules
* Fixed persistent change issue with dynamic records after the API started
returning new fields under `config`
/cc @istr @viranch going to let this one sit for a bit since there's some fairly meaningful fixes/changes.
> v0.0.4 version bump & changelog update

- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Monitors deleted or unlinked from the portal are not detected today. This PR handles that.
It also logs all the things detected out of sync by _extra_changes rather than exiting on detecting any one change. This helps inform users of all changes that will be made.
> Detect missing monitors, log all planned changes

- CHANGELOG.md
- README.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Ran into a show stopper problem with TCP monitors: NS1 errors out if the health-check path contains `&`, usually shows up when using query params. Root cause unknown, but HTTP monitors don't seem to have that problem.
Plus using HTTP monitors is the more appropriate way of implementing HTTP(s) healthchecks anyway.
This change will cause sync to trigger a (graceful) update for all dynamic records that use HTTP healthchecks.
> Use native HTTP monitors for HTTP(S) healthchecks

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Adds `Provider.list_zones` method to allow using `Ns1Provider` as a source of dynamic zone configs.
/cc https://github.com/octodns/octodns/pull/1026 for base functionality that will utilize this
> Implement Provider.list_zones for dynamic zone config support

- octodns_ns1/__init__.py
- setup.py
add __version__ which in my research/testing for #1096 I ran into as being a
(more) standard/recommended name for the version, per pep8.
/cc https://peps.python.org/pep-0008/#module-level-dunder-names which mentions version
/cc https://github.com/octodns/octodns/pull/1099
> Add __version__, deprecated __VERSION__

- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
In testing unrelated stuff locally I noticed that `ResourceException`s are thrown for 404s, i.e. when a zone doesn't exist and needs to be created. That makes for a really noisy and slightly scary log output for a normal use case. This code updates things so that 404s don't log.
/cc https://github.com/octodns/octodns-ns1/pull/71 @jdickson0296
> Don't log.exception on 404s, noisy when zones are being created

- CHANGELOG.md
- octodns_ns1/__init__.py
* Improved NS1 API error logging
* Misc improvements to the CI setup, documentation and fix to the release
packaging metadata
> v0.0.7 version bump & changelog update

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
This PR adds support for [DNAME](https://datatracker.ietf.org/doc/html/rfc6672), [DS](https://www.rfc-editor.org/rfc/rfc4034#section-5), and [TLSA](https://www.rfc-editor.org/rfc/rfc6698) records to the OctoDNS NS1 provider.
These records are supported in OctoDNS and by [NS1](https://www.ibm.com/docs/en/ns1-connect?topic=answers-reference-dns-record-types).
- **feat: Add support to DNAME, DS, and TLSA**
> Add support for DNAME, DS, and TLSA

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
/cc https://github.com/octodns/octodns/pull/1182
> Healthcheck protocol ICMP support & check for unsupported protocols (UDP)

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
> Throw error on unsupported continents

- CHANGELOG.md
- octodns_ns1/__init__.py
* `geo` record support removed, records should be migrated to `dynamic` before
upgrading.
* `SPF` record support removed, records should be migrated to `TXT` before
upgrading.
* DNAME, DS, and TLSA record type support added.
* Validate that healthcheck protocol is supported (HTTP, HTTPS, ICMP, TCP)
* Validate that continent is supported (Antarctica is supported by octoDNS but not by NS1)
* Address pending octoDNS 2.x deprecations, require minimum of 1.5.x
> Version 1.0.0 version bump & changelog update

- CHANGELOG.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
Removal of `geo` support went too far and took out some checks for non-dynamic `A`/`AAAA` records. This puts them back. 
Tests still required.
/cc https://github.com/octodns/octodns-ns1/commit/478d82bd5bd6de79d440f834e5693270fef8ab40#r156480474 @mtgagnon
> Fix handling of non-dynamic A/AAAA records with tier > 1

- CHANGELOG.md
- octodns_ns1/__init__.py
* Restore handling of tier > 1 advanced A/AAAA records that are not dynamic
> Version 1.0.1 version bump & changelog update

- .changelog/4c3c775e9fd343089403d6071d8d0bfd.md
- .changelog/c21ee7ef4f6546ee813441d051777436.md
- octodns_ns1/__init__.py
- tests/test_provider_ns1.py
_data_for_SPF does not handle the case where 'short_answers' does not exist in the answer. This creates issues when we have TXT records that are filter chain records. This patch addresses this by adding a try catch, could also do an if/else checking for the key.
> make sure we handle TXT/SPF records with no short answers
